package entities.behavior;

/*Generated by MPS */


public class IntType_BehaviorDescriptor extends PrimitiveType_BehaviorDescriptor {
  public IntType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "entities.structure.IntType";
  }
}
