package entities.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public interface IResourceContent_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
}
