package entities.behavior;

/*Generated by MPS */


public abstract class PrimitiveType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public PrimitiveType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "entities.structure.PrimitiveType";
  }
}
