package entities.behavior;

/*Generated by MPS */


public class StringType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public StringType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "entities.structure.StringType";
  }
}
