package entities.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class EntityResource_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public EntityResource_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "entities.structure.EntityResource";
  }
}
