package entities.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class EntityResource extends BaseConcept {
  public static final String concept = "entities.structure.EntityResource";
  public static final String CONTENTS = "contents";

  public EntityResource(SNode node) {
    super(node);
  }

  public int getContentsesCount() {
    return this.getChildCount(EntityResource.CONTENTS);
  }

  public Iterator<IResourceContent> contentses() {
    return this.children(IResourceContent.class, EntityResource.CONTENTS);
  }

  public List<IResourceContent> getContentses() {
    return this.getChildren(IResourceContent.class, EntityResource.CONTENTS);
  }

  public void addContents(IResourceContent node) {
    this.addChild(EntityResource.CONTENTS, node);
  }

  public void insertContents(IResourceContent prev, IResourceContent node) {
    this.insertChild(prev, EntityResource.CONTENTS, node);
  }

  public static EntityResource newInstance(SModel sm, boolean init) {
    return (EntityResource) SModelUtil_new.instantiateConceptDeclaration("entities.structure.EntityResource", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static EntityResource newInstance(SModel sm) {
    return EntityResource.newInstance(sm, false);
  }
}
