package entities.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class EntityAttribute extends BaseConcept implements INamedConcept {
  public static final String concept = "entities.structure.EntityAttribute";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String TYPE = "type";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public EntityAttribute(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(EntityAttribute.NAME);
  }

  public void setName(String value) {
    this.setProperty(EntityAttribute.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(EntityAttribute.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(EntityAttribute.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(EntityAttribute.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(EntityAttribute.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(EntityAttribute.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(EntityAttribute.VIRTUAL_PACKAGE, value);
  }

  public Type getType() {
    return (Type) this.getChild(Type.class, EntityAttribute.TYPE);
  }

  public void setType(Type node) {
    super.setChild(EntityAttribute.TYPE, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(EntityAttribute.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, EntityAttribute.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, EntityAttribute.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(EntityAttribute.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, EntityAttribute.SMODEL_ATTRIBUTE, node);
  }

  public static EntityAttribute newInstance(SModel sm, boolean init) {
    return (EntityAttribute) SModelUtil_new.instantiateConceptDeclaration("entities.structure.EntityAttribute", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static EntityAttribute newInstance(SModel sm) {
    return EntityAttribute.newInstance(sm, false);
  }
}
