package entities.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Entities_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("6ede504a-c7ec-4c49-9191-3d9d23eb4bc0(entities)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
