package entities.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.lang.core.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Entity extends BaseConcept implements IResourceContent {
  public static final String concept = "entities.structure.Entity";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String ATTRIBUTES = "attributes";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Entity(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(Entity.NAME);
  }

  public void setName(String value) {
    this.setProperty(Entity.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Entity.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Entity.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Entity.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Entity.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Entity.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Entity.VIRTUAL_PACKAGE, value);
  }

  public int getAttributesesCount() {
    return this.getChildCount(Entity.ATTRIBUTES);
  }

  public Iterator<EntityAttribute> attributeses() {
    return this.children(EntityAttribute.class, Entity.ATTRIBUTES);
  }

  public List<EntityAttribute> getAttributeses() {
    return this.getChildren(EntityAttribute.class, Entity.ATTRIBUTES);
  }

  public void addAttributes(EntityAttribute node) {
    this.addChild(Entity.ATTRIBUTES, node);
  }

  public void insertAttributes(EntityAttribute prev, EntityAttribute node) {
    this.insertChild(prev, Entity.ATTRIBUTES, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Entity.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Entity.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Entity.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Entity.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Entity.SMODEL_ATTRIBUTE, node);
  }

  public static Entity newInstance(SModel sm, boolean init) {
    return (Entity) SModelUtil_new.instantiateConceptDeclaration("entities.structure.Entity", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Entity newInstance(SModel sm) {
    return Entity.newInstance(sm, false);
  }
}
