package entities.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.INamedConcept;

public interface IResourceContent extends INamedConcept {
  public static final String concept = "entities.structure.IResourceContent";
}
