package entities.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PrimitiveType extends Type {
  public static final String concept = "entities.structure.PrimitiveType";

  public PrimitiveType(SNode node) {
    super(node);
  }

  public static PrimitiveType newInstance(SModel sm, boolean init) {
    return (PrimitiveType) SModelUtil_new.instantiateConceptDeclaration("entities.structure.PrimitiveType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PrimitiveType newInstance(SModel sm) {
    return PrimitiveType.newInstance(sm, false);
  }
}
